train: /mnt/d/Workspace/FireSmokeDetection/ai_service/datas/benchmark/train/
nc: 11
names:
    ['butter_sugar_bread', 'chicken_floss_bread', 'chicken_floss_sandwich', 'cream_puff', 'croissant', 'donut', 'muffin', 'salted_egg_sponge_cake', 'sandwich', 'sponge_cake', 'tiramisu']
