model:
  model_path: ./checkpoints/dish_scan_v6.pt
  conf_threshold: 0.8
  iou_threshold: 0.8
  classes:
    - 'butter_sugar_bread' 
    - 'chicken_floss_bread' 
    - 'chicken_floss_sandwich' 
    - 'cream_puff' 
    - 'croissant' 
    - 'donut'
    - 'muffin'
    - 'salted_egg_sponge_cake'
    - 'sandwich'
    - 'sponge_cake'
    - 'tiramisu'